#!/bin/sh

echo '<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>My Website</title>
  <link rel="stylesheet" href="/style.css">
</head>
<body>
<h1>My Website</h1>
<hr/>
<ul>'
for i in ${1}/*.html;do
    link=$(basename $i)
    if [ $link != "index.html" ];then
        title=$(sed -n 's:.*<title>\(.*\)</title>.*:\1:p' $i)
        echo '<li><a href=''"'/${link}'"''>'$title'</a></li>'
    fi
done
echo '</ul>
</body>
</html>'
