<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>My Site</title>
  <style>
    body {margin: 5% auto; background: #f2f2f2; color: #444444; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; font-size: 16px; line-height: 1.8; text-shadow: 0 1px 0 #ffffff; max-width: 73%;}
    pre {background: white; overflow-x: scroll;}
    a {border-bottom: 1px solid #444444; color: #444444; text-decoration: none;}
    a:hover {border-bottom: 0;}
  </style>
</head>
<body>
<a href="/">Home</a>
<div id="header">
<h1><?theme title?></h1>
</div>
<div id="aside">
<?theme toc?>
</div>
<div>
<?theme body?>
</div>
</body>

